language: python # Set the build language to Python

python: 3.6 # Set the version of Python to use

branches:
  only:
  - gh-pages
  - /.*/ # Watch all branches pushed to github

install:
    - pip install mkdocs # Install the required dependencies
    - gem install mdl # Install markdown linter (Ruby is already available on Travis-CI)

script:
    - mdl docs/ # Run markdown lint against docs/ folder

before_deploy:
    - mkdocs build --verbose --clean --strict # Build a local version of slides

deploy: # Deploy built mkdocs files to Github on the gh_pages branch (from master)
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: site
    on:
        branch: master